# Cartographer config - Created by BananaPuncher714
# Only permission is cartographer.admin
# It allows you to set the map center and update it.
# The only commands are /setmapcenter and /mapreload
# The map will automagically save and reload itself whenever the server restarts.
# The map will also automagically adjust the zoom so you can't zoom too far out if the map itself is smaller.

# Do NOT make the height or width smaller than 128!!
map-height: 1538
map-width: 1538

# The loading speed really depends on how large the map is. Anything below 16 will cause lag
# and 16 is already pretty fast and slightly laggy. For maps larger than 12048, use 32 or 64 or something higher.
map-load-speed: 16

# This is whether the center of the map will be in the center of a chunk or your exact position
center-chunk: true

# The DEFAULT color if there is no color for a material or if it's over the void
default-color: "255, 0, 255"

# This is how dark the water can get based on this formula: ( depth * shade ) / 100
# The result is a percent that is used to darken the color water.
# Of course, this also depends on the rgb value of the water color, but
# too small a value will not show up on the map, and too high will completely dark out deep areas.
water-shading: 100

# This option is whether or not this plugin will use the "default renderer"
# Rather, it gets the highest non-transparent block, or the highest block that blocks light.
# Using this is simpler, as it can hide tall grass, flowers, and other junk, but
# may also hide blocks like pistons, rails, chests, and other random blocks.
default-render: true

# This is the list of blocks that will NOT appear on the map ONLY when using the custom renderer.
# They can be expressed in ids or material names.
transparent-blocks:
- LEAVES_2

# Here are extra presets that will get loaded in order after loading the default config colors.
# Place them inside the presets folder.
presets: []
#- example.yml

# The order it goes in is the material name, the data value, and the RGB color value.
# It SHOULD accept ids too.
# Find the materials online here at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# The default colors can be found here: https://minecraft.gamepedia.com/Map_item_format#Color_table
# The colors below represent a 1.11.2 map pallete, before the 1.12 color update
map-colors:
    STONE,-1: "112, 112, 112"
    STONE,0: "112, 112, 112"
    STONE,1: "151, 109, 77"
    STONE,2: "151, 109, 77"
    STONE,3: "255, 252, 245"
    STONE,4: "255, 252, 245"
    STONE,5: "112, 112, 112"
    STONE,6: "112, 112, 112"
    GRASS,0: "127, 178, 56"
    DIRT,-1: "151, 109, 77"
    DIRT,0: "151, 109, 77"
    DIRT,1: "151, 109, 77"
    DIRT,2: "129, 86, 49"
    COBBLESTONE,0: "164, 168, 184"
    WOOD,-1: "143, 119, 72"
    WOOD,0: "143, 119, 72"
    WOOD,1: "129, 86, 49"
    WOOD,2: "247, 233, 163"
    WOOD,3: "151, 109, 77"
    WOOD,4: "216, 127, 51"
    WOOD,5: "102, 76, 51"
    BEDROCK,0: "112, 112, 112"
    WATER,-1: "64, 64, 255"
    STATIONARY_WATER,-1: "64, 64, 255"
    LAVA,-1: "255, 0, 0"
    STATIONARY_LAVA,-1: "255, 0, 0"
    SAND,-1: "247, 233, 163"
    SAND,0: "247, 233, 163"
    SAND,1: "216, 127, 51"
    GRAVEL,0: "112, 112, 112"
    GOLD_ORE,0: "112, 112, 112"
    IRON_ORE,0: "112, 112, 112"
    COAL_ORE,0: "112, 112, 112"
    LOG,-1: "143, 119, 72"
    LOG,0: "143, 119, 72"
    LOG,1: "129, 86, 49"
    LOG,2: "247, 233, 163"
    LOG,3: "151, 109, 77"
    LOG,4: "129, 86, 49"
    LOG,5: "102, 76, 51"
    LOG,6: "255, 252, 245"
    LOG,7: "129, 86, 49"
    LOG,8: "129, 86, 49"
    LOG,9: "102, 76, 51"
    LOG,10: "255, 252, 245"
    LOG,11: "129, 86, 49"
    LEAVES,-1: "0, 124, 0"
    SPONGE,-1: "229, 229, 51"
    LAPIS_ORE,0: "112, 112, 112"
    LAPIS_BLOCK,0: "74, 128, 255"
    DISPENSER,-1: "112, 112, 112"
    SANDSTONE,-1: "247, 233, 163"
    NOTE_BLOCK,0: "143, 119, 72"
    COBWEB,0: "199, 199, 199"
    WOOL,-1: "255, 255, 255"
    WOOL,0: "255, 255, 255"
    WOOL,1: "216, 127, 51"
    WOOL,2: "178, 76, 216"
    WOOL,3: "102, 153, 216"
    WOOL,4: "229, 229, 51"
    WOOL,5: "127, 204, 25"
    WOOL,6: "242, 127, 165"
    WOOL,7: "76, 76, 76"
    WOOL,8: "153, 153, 153"
    WOOL,9: "76, 127, 153"
    WOOL,10: "127, 63, 178"
    WOOL,11: "51, 76, 178"
    WOOL,12: "102, 76, 51"
    WOOL,13: "102, 127, 51"
    WOOL,14: "153, 51, 51"
    WOOL,15: "25, 25, 25"
    GOLD_BLOCK,0: "250, 238, 77"
    IRON_BLOCK,0: "167, 167, 167"
    DOUBLE_STEP,-1: "112, 112, 112"
    DOUBLE_STEP,0: "112, 112, 112"
    DOUBLE_STEP,1: "247, 233, 163"
    DOUBLE_STEP,2: "143, 119, 72"
    DOUBLE_STEP,3: "112, 112, 112"
    DOUBLE_STEP,4: "153, 51, 51"
    DOUBLE_STEP,5: "112, 112, 112"
    DOUBLE_STEP,6: "112, 2, 0"
    DOUBLE_STEP,7: "255, 252, 245"
    DOUBLE_STEP,8: "112, 112, 112"
    DOUBLE_STEP,9: "247, 233, 163"
    STEP,-1: "112, 112, 112"
    STEP,0: "112, 112, 112"
    STEP,1: "247, 233, 163"
    STEP,2: "143, 119, 72"
    STEP,3: "112, 112, 112"
    STEP,4: "153, 51, 51"
    STEP,5: "112, 112, 112"
    STEP,6: "112, 2, 0"
    STEP,7: "255, 252, 245"
    BRICK,0: "153, 51, 51"
    TNT,-1: "255, 0, 0"
    BOOKSHELF,0: "143, 119, 72"
    MOSSY_COBBLESTONE,0: "112, 112, 112"
    OBSIDIAN,-1: "25, 25, 25"
    WOOD_STAIRS,-1: "143, 119, 72"
    DIAMOND_ORE,0: "112, 112, 112"
    DIAMOND_BLOCK,0: "92, 219, 213"
    WORKBENCH,0: "143, 119, 72"
    SOIL,-1: "151, 109, 77"
    FURNACE,-1: "112, 112, 112"
    BURNING_FURNACE,-1: "112, 112, 112"
    COBBLESTONE_STAIRS,-1: "112, 112, 112"
    REDSTONE_ORE,0: "112, 112, 112"
    GLOWING_REDSTONE_ORE,0: "112, 112, 112"
    ICE,0: "160, 160, 255"
    SNOW_BLOCK,0: "255, 255, 255"
    CLAY,0: "164, 168, 184"
    JUKEBOX,0: "151, 109, 77"
    PUMPKIN,-1: "216, 127, 51"
    NETHERRACK,0: "112, 2, 0"
    SOUL_SAND,0: "102, 76, 51"
    GLOWSTONE,0: "247, 233, 163"
    JACK_O_LANTERN,-1: "216, 127, 51"
    MONSTER_EGGS,-1: "164, 168, 184"
    SMOOTH_BRICK,-1: "112, 112, 112"
    HUGE_MUSHROOM_1,-1: "151, 109, 77"
    HUGE_MUSHROOM_1,0: "247, 233, 163"
    HUGE_MUSHROOM_1,10: "247, 233, 163"
    HUGE_MUSHROOM_1,11: "247, 233, 163"
    HUGE_MUSHROOM_1,12: "247, 233, 163"
    HUGE_MUSHROOM_1,13: "247, 233, 163"
    HUGE_MUSHROOM_1,15: "199, 199, 199"
    HUGE_MUSHROOM_2,-1: "153, 51, 51"
    HUGE_MUSHROOM_2,0: "247, 233, 163"
    HUGE_MUSHROOM_2,10: "247, 233, 163"
    HUGE_MUSHROOM_2,11: "247, 233, 163"
    HUGE_MUSHROOM_2,12: "247, 233, 163"
    HUGE_MUSHROOM_2,13: "247, 233, 163"
    HUGE_MUSHROOM_2,15: "199, 199, 199"
    MELON_BLOCK,0: "127, 204, 25"
    BRICK_STAIRS,-1: "153, 51, 51"
    SMOOTH_STAIRS,-1: "112, 112, 112"
    MYCELIUM,0: "127, 63, 178"
    NETHER_BRICK,0: "112, 2, 0"
    NETHER_BRICK_STAIRS,-1: "112, 2, 0"
    ENDER_STONE,0: "247, 233, 163"
    REDSTONE_LAMP_OFF,0: "112, 2, 0"
    REDSTONE_LAMP_ON,0: "216, 127, 51"
    DOUBLE_WOOD_STEP,-1: "143, 119, 72"
    DOUBLE_WOOD_STEP,0: "143, 119, 72"
    DOUBLE_WOOD_STEP,1: "129, 86, 49"
    DOUBLE_WOOD_STEP,2: "247, 233, 163"
    DOUBLE_WOOD_STEP,3: "151, 109, 77"
    DOUBLE_WOOD_STEP,4: "216, 127, 51"
    DOUBLE_WOOD_STEP,5: "216, 127, 51"
    DOUBLE_WOOD_STEP,6: "102, 76, 51"
    WOOD_STEP,-1: "143, 119, 72"
    WOOD_STEP,0: "143, 119, 72"
    WOOD_STEP,1: "129, 86, 49"
    WOOD_STEP,2: "247, 233, 163"
    WOOD_STEP,3: "151, 109, 77"
    WOOD_STEP,4: "216, 127, 51"
    WOOD_STEP,5: "216, 127, 51"
    WOOD_STEP,6: "102, 76, 51"
    SANDSTONE_STAIRS,-1: "247, 233, 163"
    EMERALD_ORE,0: "112, 112, 112"
    EMERALD_BLOCK,0: "0, 217, 58"
    SPRUCE_WOOD_STAIRS,-1: "129, 86, 49"
    BIRCH_WOOD_STAIRS,-1: "247, 233, 163"
    JUNGLE_WOOD_STAIRS,-1: "151, 109, 77"
    COMMAND,-1: "102, 76, 51"
    COMMAND_CHAIN,-1: "102, 127, 51"
    COMMAND_REPEATING,-1: "127, 63, 178"
    REDSTONE_BLOCK,0: "255, 0, 0"
    QUARTZ_ORE,0: "112, 2, 0"
    QUARTZ_BLOCK,-1: "255, 252, 245"
    DROPPER,-1: "112, 112, 112"
    STAINED_CLAY,-1: "255, 255, 255"
    STAINED_CLAY,0: "255, 255, 255"
    STAINED_CLAY,1: "216, 127, 51"
    STAINED_CLAY,2: "178, 76, 216"
    STAINED_CLAY,3: "102, 153, 216"
    STAINED_CLAY,4: "229, 229, 51"
    STAINED_CLAY,5: "127, 204, 25"
    STAINED_CLAY,6: "242, 127, 165"
    STAINED_CLAY,7: "76, 76, 76"
    STAINED_CLAY,8: "153, 153, 153"
    STAINED_CLAY,9: "76, 127, 153"
    STAINED_CLAY,10: "127, 63, 178"
    STAINED_CLAY,11: "51, 76, 178"
    STAINED_CLAY,12: "102, 76, 51"
    STAINED_CLAY,13: "102, 127, 51"
    STAINED_CLAY,14: "153, 51, 51"
    STAINED_CLAY,15: "25, 25, 25"
    LEAVES_2,-1: "0, 124, 0"
    LOG_2,-1: "216, 127, 51"
    LOG_2,0: "216, 127, 51"
    LOG_2,4: "112, 112, 112"
    LOG_2,8: "112, 112, 112"
    LOG_2,1: "102, 76, 51"
    LOG_2,5: "102, 76, 51"
    LOG_2,9: "102, 76, 51"
    ACACIA_STAIRS,-1: "216, 127, 51"
    DARK_OAK_STAIRS,-1: "102, 76, 51"
    PRISMARINE,-1: "76, 127, 153"
    PRISMARINE,0: "76, 127, 153"
    PRISMARINE,1: "92, 219, 213"
    PRISMARINE,2: "92, 219, 213"
    SEA_LANTERN,0: "255, 252, 245"
    HAY_BLOCK,0: "229, 229, 51"
    HARD_CLAY,-1: "216, 127, 51"
    COAL_BLOCK,0: "25, 25, 25"
    PACKED_ICE,0: "160, 160, 255"
    RED_SANDSTONE,-1: "216, 127, 51"
    RED_SANDSTONE_STAIRS,-1: "216, 127, 51"
    STONE_SLAB2,-1: "216, 127, 51"
    PURPUR_BLOCK,0: "178, 76, 216"
    PURPUR_PILLAR,-1: "178, 76, 216"
    PURPUR_STAIRS,-1: "178, 76, 216"
    PURPUR_SLAB,-1: "178, 76, 216"
    END_BRICKS,0: "247, 233, 163"
    GRASS_PATH,0: "151, 109, 77"
    MAGMA,0: "112, 2, 0"
    NETHER_WART_BLOCK,0: "112, 2, 0"
    RED_NETHER_BRICK,0: "112, 2, 0"
    BONE_BLOCK,-1: "247, 233, 163"
    STRUCTURE_BLOCK,-1: "153, 153, 153"
    OBSERVER,-1: "112, 112, 112"
